import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { LogOutBtn } from './LogOutBtn'
import { cookies } from 'next/headers'
import DarkMode from './DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)

  let cookie = cookies().get('mode')

  console.log(session)
  return (
    <html lang="en">
      <body className={
        cookie != undefined && cookie.value == 'dark' 
          ? 'dark-mode'
          : ''
      }>
        <div className="navbar"> 
          <Link href="/" className="logo">Forum</Link> 
          <Link href="/list">List</Link> 
          { 
            session 
              ? <a>{session.user.name} <LogOutBtn/> </a> 
              : <LoginBtn/>
          }
          <DarkMode/>
        </div>  
        {children}
      </body>
    </html>
  )
}
